name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - run: zig fmt --check .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - uses: extractions/setup-just@v1

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm install -g wasm4

      - run: just bundle

      - uses: actions/upload-artifact@v2
        with:
          name: Cartridge
          path: zig-out/lib/cart.wasm

      - run: mkdir public && mv bundle/index.html public/

      - uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
